#[cfg(target_os = "windows")]
use ffmpeg_next as ffmpeg;
#[cfg(target_os = "windows")]
use ffmpeg::ffi;
#[cfg(target_os = "windows")]
use std::mem::ManuallyDrop;

// ── Annex-B / SPS helpers ─────────────────────────────────────────────────────

/// Returns `true` if `data` (Annex-B) contains at least one SPS NAL unit (type 7).
/// Used to decide whether we need to prepend SPS+PPS from the encoder extradata.
#[cfg(target_os = "windows")]
fn has_sps_annexb(data: &[u8]) -> bool {
    let len = data.len();
    let mut i = 0;
    while i + 3 <= len {
        let sc4 = i + 4 <= len
            && data[i] == 0 && data[i+1] == 0 && data[i+2] == 0 && data[i+3] == 1;
        let sc3 = !sc4
            && data[i] == 0 && data[i+1] == 0 && data[i+2] == 1;
        if sc4 {
            if i + 5 <= len && (data[i+4] & 0x1F) == 7 { return true; }
            i += 4;
        } else if sc3 {
            if i + 4 <= len && (data[i+3] & 0x1F) == 7 { return true; }
            i += 3;
        } else {
            i += 1;
        }
    }
    false
}

/// Converts an AVCDecoderConfigurationRecord (AVCC extradata from AVCodecContext.extradata)
/// into Annex-B SPS+PPS bytes suitable for prepending to a keyframe packet.
#[cfg(target_os = "windows")]
fn avcc_extradata_to_annexb(avcc: &[u8]) -> Vec<u8> {
    if avcc.len() < 7 { return Vec::new(); }
    let mut out = Vec::new();
    let num_sps = (avcc[5] & 0x1F) as usize;
    let mut i = 6;
    for _ in 0..num_sps {
        if i + 2 > avcc.len() { return out; }
        let n = u16::from_be_bytes([avcc[i], avcc[i+1]]) as usize;
        i += 2;
        if i + n > avcc.len() { return out; }
        out.extend_from_slice(&[0, 0, 0, 1]);
        out.extend_from_slice(&avcc[i..i+n]);
        i += n;
    }
    if i >= avcc.len() { return out; }
    let num_pps = avcc[i] as usize;
    i += 1;
    for _ in 0..num_pps {
        if i + 2 > avcc.len() { return out; }
        let n = u16::from_be_bytes([avcc[i], avcc[i+1]]) as usize;
        i += 2;
        if i + n > avcc.len() { return out; }
        out.extend_from_slice(&[0, 0, 0, 1]);
        out.extend_from_slice(&avcc[i..i+n]);
        i += n;
    }
    out
}

// ── Capture diagnostic logger ───────────────────────────────────────────────────
// Writes to stderr AND appends to %TEMP%\specter_capture_debug.txt so diagnostics
// are visible both when running from a terminal and as a persistent file the user
// can share after a test session.
#[cfg(target_os = "windows")]
fn capture_log(msg: &str) {
    eprintln!("{msg}");
    use std::io::Write;
    let path = std::env::temp_dir().join("specter_capture_debug.txt");
    if let Ok(mut f) = std::fs::OpenOptions::new().create(true).append(true).open(path) {
        let _ = writeln!(f, "{msg}");
    }
}

// ── D3D11VA zero-copy structs ─────────────────────────────────────────────────
// These types exist in FFmpeg's public ABI (hwcontext_d3d11va.h) but are not
// generated by the bindgen pass in ffmpeg-sys-next, so we define them manually.
//
// Layout is stable across all FFmpeg versions that support D3D11VA.
#[cfg(target_os = "windows")]
#[repr(C)]
struct AvD3D11VaDeviceCtx {
    device:         *mut std::ffi::c_void,   // ID3D11Device*
    device_context: *mut std::ffi::c_void,   // ID3D11DeviceContext*
    video_device:   *mut std::ffi::c_void,   // ID3D11VideoDevice*  (filled by init)
    video_context:  *mut std::ffi::c_void,   // ID3D11VideoContext* (filled by init)
    lock:    Option<unsafe extern "C" fn(*mut std::ffi::c_void)>,
    unlock:  Option<unsafe extern "C" fn(*mut std::ffi::c_void)>,
    lock_ctx: *mut std::ffi::c_void,
}

#[cfg(target_os = "windows")]
#[repr(C)]
struct AvD3D11VaFramesCtx {
    texture:    *mut std::ffi::c_void,  // ID3D11Texture2D* (NULL = auto alloc)
    bind_flags: u32,                    // UINT BindFlags for pool textures
    misc_flags: u32,                    // UINT MiscFlags  for pool textures
}

// ── D3D11VA encoder state ────────────────────────────────────────────────────
// Held by StatefulEncoder when the GPU zero-copy path is active.
#[cfg(target_os = "windows")]
struct D3d11vaState {
    video_dev:  windows::Win32::Graphics::Direct3D11::ID3D11VideoDevice,
    video_ctx:  windows::Win32::Graphics::Direct3D11::ID3D11VideoContext,
    d3d_ctx:    windows::Win32::Graphics::Direct3D11::ID3D11DeviceContext,
    vp_enum:    windows::Win32::Graphics::Direct3D11::ID3D11VideoProcessorEnumerator,
    vp:         windows::Win32::Graphics::Direct3D11::ID3D11VideoProcessor,
    /// Intermediate non-shared BGRA texture; WGC frames are DXGI shared resources
    /// which many drivers cannot read as VP input views (produces black output).
    /// We CopyResource (pure GPU) into this each frame before the VP blit.
    blit_tex:   Option<windows::Win32::Graphics::Direct3D11::ID3D11Texture2D>,
    /// Cached VP input view for blit_tex. Creating this view every frame at
    /// 60 fps is the dominant per-frame D3D11 allocation. Invalidated only
    /// when blit_tex is recreated (source resolution change). Safe to cache:
    /// blit_tex's lifecycle is fully owned by our own code (see stage_frame),
    /// unlike the NV12 pool textures below.
    input_view: Option<windows::Win32::Graphics::Direct3D11::ID3D11VideoProcessorInputView>,
}

// SAFETY: D3D11VA state is only ever accessed from the single capture thread.
#[cfg(target_os = "windows")]
unsafe impl Send for D3d11vaState {}

// ── StatefulEncoder Drop: flush NVENC pipeline before freeing ────────────────
// NVENC requires the encoder to be drained (send EOF + receive all remaining
// packets) before NvEncDestroyEncoder is called.  Skipping this step on
// consumer GPUs causes the NVIDIA driver to raise a structured exception that
// kills the process.
//
// The capture thread calls drain() explicitly after its frame loop exits so the
// drain always runs while d3d_device / d3d_context are still alive in the
// thread closure.  Drop is a safety net for any other drop site.
#[cfg(target_os = "windows")]
impl Drop for StatefulEncoder {
    fn drop(&mut self) {
        if self.device_lost || std::thread::panicking() {
            // D3D11/NVENC is in an invalid state or the thread is unwinding.
            // Skip drain + NvEncDestroyEncoder — calling either on a lost device
            // raises a Windows SEH that kills the process. Leak the encoder;
            // the driver reclaims the NVENC session at process exit.
            capture_log("[encoder] drop: skipping drain (device_lost or panicking)");
            self.d3d11va = None;
            return;
        }
        if !self.drained {
            self.drain();
        }
        if !self.drained {
            // drain() did not reach AVERROR_EOF — calling NvEncDestroyEncoder on
            // an encoder with queued frames raises a Windows SEH that kills the
            // process. Leak the encoder; driver reclaims at process exit.
            capture_log("[encoder] drop: drain incomplete — leaking encoder to prevent SEH crash");
            self.d3d11va = None;
            return;
        }
        capture_log("[encoder] drop: releasing d3d11va state");
        self.d3d11va = None;
        // SAFETY: drain() confirmed AVERROR_EOF; NvEncDestroyEncoder is safe.
        unsafe { ManuallyDrop::drop(&mut self.encoder); }
        capture_log("[encoder] drop: complete");
    }
}

// ── Pure H.264 D3D11VA encoder ───────────────────────────────────────────────
// Created ONCE per capture session. GPU-only zero-copy path: no CPU involvement.
//
// Encode path:
//   DXGI Desktop texture → GPU-only BGRA tex → VideoProcessor BGRA→NV12 → hw encoder
//   Zero CPU readback, zero PCIe copy. Target: 60 fps, ~2 ms/frame.
//
// Hardware encoder is selected by GPU vendor (see GpuVendor in capture/mod.rs):
// NVENC on NVIDIA, AMF on AMD. If D3D11VA or a supported hw encoder is unavailable
// on the system, capture initialization fails immediately — no CPU fallback is provided.
#[cfg(target_os = "windows")]
pub struct StatefulEncoder {
    // ManuallyDrop so we can skip NvEncDestroyEncoder when D3D11 is in a lost
    // or invalid state — calling it with queued frames on a bad device raises
    // a Windows structured exception (SEH) that bypasses Rust's panic machinery
    // and kills the process.  We drop it explicitly in the normal path; in the
    // device-lost / panic path we intentionally leak it (NVENC session is
    // reclaimed by the driver when the process exits).
    encoder:     ManuallyDrop<ffmpeg::encoder::Video>,
    frame:       ffmpeg::frame::Video,
    pts:         i64,
    d3d11va:     Option<D3d11vaState>,
    /// Set when DXGI or D3D11 reports a device error; causes drain() to no-op
    /// and Drop to skip NvEncDestroyEncoder, preventing SEH.
    device_lost: bool,
    /// Set to true only when drain() successfully received AVERROR_EOF, meaning
    /// NvEncDestroyEncoder (via avcodec_free_context) is safe to call.
    drained: bool,
    /// Timestamp stored by submit_frame; returned with the NalUnit from try_harvest.
    pending_ts:  u64,
    pub codec_name: &'static str,
}

#[cfg(target_os = "windows")]
impl StatefulEncoder {
    // ── Explicit pipeline drain ───────────────────────────────────────────────
    // Flush D3D11 + drain NVENC to a clean EOF so avcodec_free_context (called
    // by the encoder's own Drop) finds NvEncDestroyEncoder in a safe state.
    // Safe to call multiple times: after the first successful EOF the subsequent
    // calls return immediately (pre-drain loop is empty, send_eof → EOF on first
    // receive).  The capture thread calls this explicitly before encoder_opt drops
    // so the drain always runs while D3D11 resources are still alive.
    /// Signal that D3D11/DXGI has reported a device error.  drain() becomes a
    /// no-op and Drop skips NvEncDestroyEncoder to prevent SEH.
    pub fn mark_device_lost(&mut self) {
        self.device_lost = true;
    }

    pub fn drain(&mut self) {
        if self.device_lost {
            capture_log("[encoder] drain: skipping — device marked lost");
            return;
        }
        if let Some(ref d3d11va) = self.d3d11va {
            capture_log("[encoder] drain: flushing d3d11 context");
            unsafe { d3d11va.d3d_ctx.Flush(); }
        }
        if self.drained {
            capture_log("[encoder] drain: already drained, skipping");
            return;
        }
        capture_log(&format!("[encoder] drain: draining {} pipeline", self.codec_name));
        let mut pkt = ffmpeg::Packet::empty();
        // Pre-drain any packets already queued before sending EOF.
        loop {
            match self.encoder.receive_packet(&mut pkt) {
                Ok(()) => {}
                Err(_) => break,
            }
        }
        // Send EOF and drain until AVERROR_EOF.  When NVENC returns EAGAIN (GPU
        // still processing), sleep 1 ms before retrying so we give the GPU time
        // to finish rather than spinning through all 256 iterations instantly.
        'outer: for _ in 0..256 {
            let _ = self.encoder.send_eof();
            let mut got_eagain = false;
            loop {
                match self.encoder.receive_packet(&mut pkt) {
                    Ok(())                  => { got_eagain = false; }
                    Err(ffmpeg::Error::Eof) => {
                        capture_log("[encoder] drain: nvenc eof");
                        self.drained = true;
                        break 'outer;
                    }
                    Err(_)                  => { got_eagain = true; break; }
                }
            }
            if got_eagain {
                std::thread::sleep(std::time::Duration::from_millis(1));
            }
        }
        if !self.drained {
            capture_log("[encoder] drain: WARNING — NVENC did not reach EOF after 256 retries");
        }
        capture_log("[encoder] drain: done");
    }

    // ── Stage frame: CopyResource only ────────────────────────────────────────
    // Copy `src` (the live DXGI frame texture) into the internal blit_tex,
    // allocating or resizing it as needed.  Call this while the DXGI frame is
    // still held, then call ReleaseFrame, then call encode_from_blit — this lets
    // the game's flip chain proceed while the VideoProcessorBlt + NVENC encode
    // runs without holding the DXGI output lock.
    pub fn stage_frame(
        &mut self,
        src: &windows::Win32::Graphics::Direct3D11::ID3D11Texture2D,
    ) -> Result<(), String> {
        use windows::Win32::Graphics::Direct3D11::ID3D11Device;
        use windows::Win32::Graphics::Dxgi::Common::DXGI_SAMPLE_DESC;
        use windows::core::Interface;

        let d3d11va = self.d3d11va.as_mut().ok_or("stage_frame called on CPU-path encoder")?;

        let mut src_desc = windows::Win32::Graphics::Direct3D11::D3D11_TEXTURE2D_DESC::default();
        unsafe { src.GetDesc(&mut src_desc) };

        let verbose = self.pts <= 2 || self.pts % 300 == 0;
        if verbose {
            capture_log(&format!("[stage_frame] frame#{} src {}x{} fmt={} misc={:#x}",
                self.pts, src_desc.Width, src_desc.Height, src_desc.Format.0, src_desc.MiscFlags));
        }

        let needs_new_blit = match d3d11va.blit_tex.as_ref() {
            None => true,
            Some(t) => {
                let mut bt = windows::Win32::Graphics::Direct3D11::D3D11_TEXTURE2D_DESC::default();
                unsafe { t.GetDesc(&mut bt) };
                bt.Width != src_desc.Width || bt.Height != src_desc.Height
            }
        };
        if needs_new_blit {
            let blit_desc = windows::Win32::Graphics::Direct3D11::D3D11_TEXTURE2D_DESC {
                Width:          src_desc.Width,
                Height:         src_desc.Height,
                MipLevels:      1,
                ArraySize:      1,
                Format:         src_desc.Format,
                SampleDesc:     DXGI_SAMPLE_DESC { Count: 1, Quality: 0 },
                Usage:          windows::Win32::Graphics::Direct3D11::D3D11_USAGE_DEFAULT,
                BindFlags:      0x20 | 0x08,  // RENDER_TARGET | SHADER_RESOURCE
                CPUAccessFlags: 0,
                MiscFlags:      0,
            };
            let d3d_dev: ID3D11Device = d3d11va.video_dev.cast()
                .map_err(|e| { let m = format!("cast ID3D11Device for blit_tex: {e}"); capture_log(&m); m })?;
            let mut tex = None;
            unsafe { d3d_dev.CreateTexture2D(&blit_desc, None, Some(&mut tex)) }
                .map_err(|e| { let m = format!("CreateTexture2D(blit_tex): {e}"); capture_log(&m); m })?;
            d3d11va.blit_tex = tex;
            d3d11va.input_view = None; // blit_tex changed; cached VP input view is stale
            capture_log(&format!("[stage_frame] (re)created blit_tex {}x{}", src_desc.Width, src_desc.Height));
        }

        let blit_tex = d3d11va.blit_tex.as_ref().unwrap();
        unsafe { d3d11va.d3d_ctx.CopyResource(blit_tex, src) };
        if verbose { capture_log(&format!("[stage_frame] frame#{} CopyResource ok", self.pts)); }
        Ok(())
    }

    // ── Submit: VP blit + NVENC send_frame ────────────────────────────────────
    // VideoProcessorBlt (BGRA→NV12) + send_frame.  Must be called after
    // stage_frame() has copied the source into blit_tex.  Returns immediately
    // after send_frame — GPU starts encoding asynchronously.  Call try_harvest()
    // at the top of the NEXT capture iteration to collect the NAL without blocking.
    pub fn submit_frame(&mut self, timestamp_ms: u64) -> Result<(), String> {
        use windows::Win32::Graphics::Direct3D11::{
            D3D11_VIDEO_PROCESSOR_INPUT_VIEW_DESC,
            D3D11_VIDEO_PROCESSOR_INPUT_VIEW_DESC_0,
            D3D11_VIDEO_PROCESSOR_OUTPUT_VIEW_DESC,
            D3D11_VIDEO_PROCESSOR_OUTPUT_VIEW_DESC_0,
            D3D11_VIDEO_PROCESSOR_STREAM,
            D3D11_VPIV_DIMENSION_TEXTURE2D,
            D3D11_VPOV_DIMENSION_TEXTURE2D,
            D3D11_TEX2D_VPIV, D3D11_TEX2D_VPOV,
        };
        use windows::Win32::Foundation::BOOL;

        let d3d11va = self.d3d11va.as_mut().ok_or("submit_frame called on CPU-path encoder")?;
        let blit_tex = d3d11va.blit_tex.as_ref()
            .ok_or("submit_frame called before stage_frame — blit_tex is None")?;

        // ── Get NV12 hw frame from pool ───────────────────────────────────────
        let frame_raw = unsafe { self.frame.as_mut_ptr() };
        unsafe { ffi::av_frame_unref(frame_raw) };
        let ret = unsafe {
            ffi::av_hwframe_get_buffer(
                (*self.encoder.as_ptr()).hw_frames_ctx,
                frame_raw,
                0,
            )
        };
        if ret < 0 {
            let msg = format!("[submit_frame] frame#{} av_hwframe_get_buffer failed: {ret} (pool exhausted — a buffer NVENC/AMF is still encoding was needed again)", self.pts);
            capture_log(&msg);
            return Err(msg);
        }

        unsafe { (*frame_raw).pts = self.pts; }
        self.pts += 1;

        let nv12_tex_raw = unsafe { (*frame_raw).data[0] as *mut std::ffi::c_void };
        if nv12_tex_raw.is_null() {
            let msg = format!("[submit_frame] frame#{} hw_frame.data[0] is null", self.pts);
            capture_log(&msg);
            return Err(msg);
        }
        let nv12_tex = unsafe {
            std::mem::ManuallyDrop::new(
                <windows::Win32::Graphics::Direct3D11::ID3D11Texture2D
                    as windows::core::Interface>::from_raw(nv12_tex_raw)
            )
        };

        let verbose = self.pts <= 2 || self.pts % 300 == 0;

        // ── Get or create VP input view on blit_tex ───────────────────────────
        // Cached: blit_tex changes only on source resolution change, so the
        // same view can be reused every frame — saves one D3D11 allocation/frame.
        let input_view = if let Some(ref cached) = d3d11va.input_view {
            cached.clone()
        } else {
            let input_desc = D3D11_VIDEO_PROCESSOR_INPUT_VIEW_DESC {
                FourCC: 0,
                ViewDimension: D3D11_VPIV_DIMENSION_TEXTURE2D,
                Anonymous: D3D11_VIDEO_PROCESSOR_INPUT_VIEW_DESC_0 {
                    Texture2D: D3D11_TEX2D_VPIV { MipSlice: 0, ArraySlice: 0 },
                },
            };
            let mut input_view_opt = None;
            unsafe {
                d3d11va.video_dev.CreateVideoProcessorInputView(
                    blit_tex, &d3d11va.vp_enum, &input_desc, Some(&mut input_view_opt),
                )
            }.map_err(|e| { let m = format!("CreateVideoProcessorInputView: {e}"); capture_log(&m); m })?;
            let iv = input_view_opt.ok_or("CreateVideoProcessorInputView returned None")?;
            d3d11va.input_view = Some(iv.clone());
            iv
        };

        let array_slice = unsafe { (*frame_raw).data[1] as usize as u32 };
        let mut nv12_tex_desc = windows::Win32::Graphics::Direct3D11::D3D11_TEXTURE2D_DESC::default();
        unsafe { (*nv12_tex).GetDesc(&mut nv12_tex_desc) };
        if verbose {
            capture_log(&format!("[submit_frame] frame#{} nv12 {}x{} arr={} fmt={}",
                self.pts, nv12_tex_desc.Width, nv12_tex_desc.Height, nv12_tex_desc.ArraySize, nv12_tex_desc.Format.0));
        }

        let output_desc = if nv12_tex_desc.ArraySize > 1 {
            use windows::Win32::Graphics::Direct3D11::{
                D3D11_VPOV_DIMENSION_TEXTURE2DARRAY, D3D11_TEX2D_ARRAY_VPOV,
            };
            D3D11_VIDEO_PROCESSOR_OUTPUT_VIEW_DESC {
                ViewDimension: D3D11_VPOV_DIMENSION_TEXTURE2DARRAY,
                Anonymous: D3D11_VIDEO_PROCESSOR_OUTPUT_VIEW_DESC_0 {
                    Texture2DArray: D3D11_TEX2D_ARRAY_VPOV {
                        MipSlice: 0,
                        FirstArraySlice: array_slice,
                        ArraySize: 1,
                    },
                },
            }
        } else {
            D3D11_VIDEO_PROCESSOR_OUTPUT_VIEW_DESC {
                ViewDimension: D3D11_VPOV_DIMENSION_TEXTURE2D,
                Anonymous: D3D11_VIDEO_PROCESSOR_OUTPUT_VIEW_DESC_0 {
                    Texture2D: D3D11_TEX2D_VPOV { MipSlice: 0 },
                },
            }
        };
        // Create a fresh output view every frame rather than caching by array-slice.
        // The cache assumed FFmpeg's hw_frames pool always hands back the same
        // underlying texture object for a given array-slice index — if the pool
        // ever reallocates that texture, a cached view is left pointing at a
        // destroyed resource, and using/releasing it later is a use-after-free
        // (observed as an access violation inside d3d11.dll's Release() on a
        // corrupted vtable). One extra CreateVideoProcessorOutputView call per
        // frame is negligible next to that risk.
        let mut output_view_opt = None;
        unsafe {
            d3d11va.video_dev.CreateVideoProcessorOutputView(
                &*nv12_tex, &d3d11va.vp_enum, &output_desc, Some(&mut output_view_opt),
            )
        }.map_err(|e| { let m = format!("CreateVideoProcessorOutputView: {e}"); capture_log(&m); m })?;
        let output_view = output_view_opt.ok_or("CreateVideoProcessorOutputView returned None")?;

        // ── Color space hints (HDR detection from blit_tex format) ────────────
        {
            use windows::Win32::Graphics::Direct3D11::ID3D11VideoContext1;
            use windows::Win32::Graphics::Dxgi::Common::DXGI_COLOR_SPACE_TYPE;
            const CS_SRGB:  DXGI_COLOR_SPACE_TYPE = DXGI_COLOR_SPACE_TYPE(0);
            const CS_SCRGB: DXGI_COLOR_SPACE_TYPE = DXGI_COLOR_SPACE_TYPE(1);
            const CS_BT709: DXGI_COLOR_SPACE_TYPE = DXGI_COLOR_SPACE_TYPE(4);
            let mut blit_desc = windows::Win32::Graphics::Direct3D11::D3D11_TEXTURE2D_DESC::default();
            unsafe { blit_tex.GetDesc(&mut blit_desc) };
            let input_cs = if blit_desc.Format.0 == 10 || blit_desc.Format.0 == 11 {
                CS_SCRGB
            } else {
                CS_SRGB
            };
            use windows::core::Interface as _;
            if let Ok(vc1) = d3d11va.video_ctx.cast::<ID3D11VideoContext1>() {
                unsafe {
                    vc1.VideoProcessorSetOutputColorSpace1(&d3d11va.vp, CS_BT709);
                    vc1.VideoProcessorSetStreamColorSpace1(&d3d11va.vp, 0, input_cs);
                }
            }
        }

        let mut stream = D3D11_VIDEO_PROCESSOR_STREAM::default();
        stream.Enable        = BOOL(1);
        stream.pInputSurface = std::mem::ManuallyDrop::new(Some(input_view));

        let blt_result = unsafe {
            d3d11va.video_ctx.VideoProcessorBlt(
                &d3d11va.vp, &output_view, 0, std::slice::from_ref(&stream),
            )
        };
        // Release the input surface ManuallyDrop — output_view stays alive in the cache.
        unsafe { std::mem::ManuallyDrop::drop(&mut stream.pInputSurface) };
        blt_result.map_err(|e| { let m = format!("VideoProcessorBlt: {e}"); capture_log(&m); m })?;
        if verbose { capture_log(&format!("[submit_frame] frame#{} VideoProcessorBlt ok — submitting to NVENC", self.pts)); }

        self.encoder.send_frame(&self.frame).map_err(|e| e.to_string())?;
        self.pending_ts = timestamp_ms;
        Ok(())
    }

    // ── Non-blocking harvest: receive one encoded NAL ─────────────────────────
    // Drains all packets NVENC has queued (typically 0 on first iteration, 1
    // thereafter with delay=1).  Returns None if no packet is ready yet (EAGAIN)
    // — caller should proceed with the next frame acquisition and try again next
    // iteration.  Never sleeps or blocks.
    pub fn try_harvest(&mut self) -> Option<super::NalUnit> {
        let mut data        = Vec::new();
        let mut is_keyframe = false;
        let mut packet      = ffmpeg::Packet::empty();
        let mut pkt_bytes   = 0usize;
        let mut got         = false;
        while self.encoder.receive_packet(&mut packet).is_ok() {
            got = true;
            is_keyframe = packet.is_key();
            if let Some(d) = packet.data() {
                pkt_bytes += d.len();
                data.extend_from_slice(d);
            }
        }
        if !got { return None; }
        let verbose = self.pts <= 3 || self.pts % 300 == 0;
        if verbose {
            capture_log(&format!("[try_harvest] frame#{} bytes={} key={}", self.pts, pkt_bytes, is_keyframe));
        }
        if is_keyframe && !has_sps_annexb(&data) {
            let avcc = self.extradata();
            if !avcc.is_empty() {
                let headers = avcc_extradata_to_annexb(avcc);
                if !headers.is_empty() {
                    let mut new_data = headers;
                    new_data.extend_from_slice(&data);
                    data = new_data;
                }
            }
        }
        Some(super::NalUnit { data, is_keyframe, timestamp_ms: self.pending_ts, codec_name: self.codec_name })
    }

    // ── Blocking encode wrapper (used by encode_d3d11) ────────────────────────
    // Calls submit_frame then spins on try_harvest.  Used by callers that want
    // synchronous behaviour; the capture loops use submit_frame/try_harvest directly.
    pub fn encode_from_blit(&mut self, timestamp_ms: u64) -> Result<super::NalUnit, String> {
        self.submit_frame(timestamp_ms)?;
        for _ in 0..200 {
            if let Some(nal) = self.try_harvest() {
                return Ok(nal);
            }
            std::thread::sleep(std::time::Duration::from_millis(1));
        }
        Err(format!("{}: no packet after 200ms", self.codec_name))
    }

    // ── D3D11VA zero-copy constructor ─────────────────────────────────────────
    // Shares the caller's D3D11 device+context so textures from DXGI Desktop
    // Duplication can be passed directly to NVENC without staging or PCIe copy.
    //
    // Returns Err if NVENC or the D3D11 Video API is unavailable on this system.
    // There are NO fallbacks — this is the only encoding path.
    pub fn new_d3d11va(
        src_w: u32, src_h: u32,
        enc_w: u32, enc_h: u32,
        config: &super::CaptureConfig,
        d3d_device: &windows::Win32::Graphics::Direct3D11::ID3D11Device,
        d3d_context: &windows::Win32::Graphics::Direct3D11::ID3D11DeviceContext,
        codec_name: &str,
    ) -> Result<Self, String>
    {
        use windows::Win32::Graphics::Direct3D11::{
            ID3D11VideoDevice, ID3D11VideoContext,
            D3D11_VIDEO_PROCESSOR_CONTENT_DESC,
            D3D11_VIDEO_FRAME_FORMAT_PROGRESSIVE,
            D3D11_VIDEO_USAGE_PLAYBACK_NORMAL,
        };
        use windows::Win32::Graphics::Dxgi::Common::DXGI_RATIONAL;
        use windows::core::Interface;

        ffmpeg::init().map_err(|e| format!("ffmpeg init failed: {e}"))?;
        let codec = ffmpeg::encoder::find_by_name(codec_name)
            .ok_or_else(|| format!("{codec_name} codec not found"))?;

        // ── 1. Allocate D3D11VA hw device context ─────────────────────────────
        let device_ctx_buf = unsafe {
            ffi::av_hwdevice_ctx_alloc(ffi::AVHWDeviceType::AV_HWDEVICE_TYPE_D3D11VA)
        };
        if device_ctx_buf.is_null() {
            return Err("[d3d11va] av_hwdevice_ctx_alloc failed".to_string());
        }

        unsafe {
            let device_ctx = (*device_ctx_buf).data as *mut ffi::AVHWDeviceContext;
            let d3d11_hwctx = (*device_ctx).hwctx as *mut AvD3D11VaDeviceCtx;
            // FFmpeg's hwdevice free callback (d3d11va_device_free) unconditionally
            // calls Release() on both `device` and `device_context` when the hw
            // device context is torn down — it takes ownership of one ref to each.
            // d3d11va_device_init does NOT AddRef them itself (it only
            // QueryInterfaces the video_device/video_context fields, which AddRef
            // separately via the QueryInterface contract). Handing over the raw
            // pointer from an existing owned clone without an extra AddRef here
            // means FFmpeg's teardown Release() is uncompensated — a double
            // release of the shared/cached D3D11 device once this function's own
            // owned clone (`d3d_device`/`d3d_context`) also drops at end of scope.
            // Clone (AddRef) + forget to hand FFmpeg a reference it can legitimately
            // own and release exactly once.
            let device_owned = d3d_device.clone();
            let device_context_owned = d3d_context.clone();
            (*d3d11_hwctx).device         = device_owned.as_raw() as *mut std::ffi::c_void;
            (*d3d11_hwctx).device_context = device_context_owned.as_raw() as *mut std::ffi::c_void;
            std::mem::forget(device_owned);
            std::mem::forget(device_context_owned);
            // lock/unlock stay NULL — all D3D11 calls happen on the capture thread.
        }

        if unsafe { ffi::av_hwdevice_ctx_init(device_ctx_buf) } < 0 {
            unsafe { ffi::av_buffer_unref(&mut (device_ctx_buf as *mut _)); }
            return Err("[d3d11va] av_hwdevice_ctx_init failed".to_string());
        }

        // ── 2. Create NV12 hw frames context (pool of 2) ─────────────────────
        let frames_ctx_buf = unsafe { ffi::av_hwframe_ctx_alloc(device_ctx_buf) };
        if frames_ctx_buf.is_null() {
            unsafe {
                let mut p = device_ctx_buf;
                ffi::av_buffer_unref(&mut p);
            }
            return Err("[d3d11va] av_hwframe_ctx_alloc failed".to_string());
        }

        unsafe {
            let frames_ctx = (*frames_ctx_buf).data as *mut ffi::AVHWFramesContext;
            (*frames_ctx).format           = ffi::AVPixelFormat::AV_PIX_FMT_D3D11;
            (*frames_ctx).sw_format        = ffi::AVPixelFormat::AV_PIX_FMT_NV12;
            (*frames_ctx).width            = enc_w as std::os::raw::c_int;
            (*frames_ctx).height           = enc_h as std::os::raw::c_int;
            // Reverted to 2 (briefly tried 4 to add timing headroom, but that change
            // is suspected of introducing a NEW clean failure — av_hwframe_ctx_init
            // returning an error — never observed with depth 2 across many prior
            // tests. Reverting to isolate that variable; the output_views fix
            // (removed entirely — see below) is the debugger-confirmed fix and
            // doesn't depend on pool depth. Must match "surfaces" dict value below.
            (*frames_ctx).initial_pool_size = 2;
            // Set D3D11_BIND_RENDER_TARGET on pool textures so we can create
            // VideoProcessorOutputViews on them.
            let d3d11_fctx = (*frames_ctx).hwctx as *mut AvD3D11VaFramesCtx;
            // 0x20 = D3D11_BIND_RENDER_TARGET | 0x400 = D3D11_BIND_VIDEO_ENCODER
            (*d3d11_fctx).bind_flags = 0x20 | 0x400;
        }

        if unsafe { ffi::av_hwframe_ctx_init(frames_ctx_buf) } < 0 {
            unsafe {
                let mut f = frames_ctx_buf;
                ffi::av_buffer_unref(&mut f);
                let mut d = device_ctx_buf;
                ffi::av_buffer_unref(&mut d);
            }
            return Err("[d3d11va] av_hwframe_ctx_init failed".to_string());
        }

        // ── 3. Open NVENC encoder with hw_frames_ctx ──────────────────────────
        let ctx   = ffmpeg::codec::context::Context::new_with_codec(codec);
        let mut video = ctx.encoder().video()
            .map_err(|e| format!("encoder().video() failed: {e}"))?;
        video.set_width(enc_w);
        video.set_height(enc_h);
        video.set_format(ffmpeg::util::format::Pixel::D3D11);
        video.set_bit_rate(config.bitrate as usize);
        video.set_time_base(ffmpeg::Rational::new(1, config.fps as i32));

        unsafe {
            let raw = video.as_mut_ptr();
            // Give AVCodecContext a reference to the hw frames context.
            (*raw).hw_frames_ctx = ffi::av_buffer_ref(frames_ctx_buf);
        }

        let mut dict = ffmpeg::Dictionary::new();
        // Options shared across encoder backends — both NVENC and AMF accept these
        // exact key/value spellings (verified against `ffmpeg -h encoder=<name>`).
        dict.set("profile",        "high");  // H.264 High Profile (matches avc1.640033)
        dict.set("level",          "51");    // Level 5.1 — covers 2560×1440@60fps
        dict.set("bf",             "0");
        // maxrate caps peak burst so the upload link is never overrun.
        dict.set("maxrate",        &config.bitrate.to_string());
        // vbv_bufsize = 1× bitrate (kbits): 1-second burst budget keeps peak
        // packet size tighter than 2× — acceptable for screen sharing where
        // minimising upstream bandwidth is the priority.
        dict.set("vbv-bufsize",    &(config.bitrate / 1000).to_string());
        // Force an IDR every 2 seconds so P-frame reference error cannot accumulate
        // across a long GOP.  Without an explicit GOP size the encoder defaults to
        // ~250 frames (>4 s at 60 fps), causing progressive blocking/smearing as each
        // P-frame inherits and amplifies the previous frame's quantisation error.
        dict.set("g",              &(config.fps * 2).to_string());

        match codec_name {
            "h264_amf" => {
                // AMD AMF encoder (Radeon GPUs). Option names/values verified against
                // `ffmpeg -h encoder=h264_amf` — AMF's private options differ from
                // NVENC's, unlike the shared block above.
                // lowlatency_high_quality: closest AMF analog to NVENC's p4/hq combo —
                // low-latency usage profile with the higher quality preset.
                dict.set("usage",          "lowlatency_high_quality");
                dict.set("quality",        "quality");
                // vbr_latency: latency-constrained VBR, AMF's analog to NVENC's plain "vbr".
                dict.set("rc",             "vbr_latency");
                // vbaq: AMF's spatial-AQ equivalent — redistributes bits toward visually
                // detailed areas (sharp edges, text), same rationale as NVENC's spatial-aq.
                dict.set("vbaq",           "1");
                // enforce_hrd: makes maxrate/vbv-bufsize actually constrain the bitstream,
                // mirroring NVENC's vbr+maxrate/vbv-bufsize behavior.
                dict.set("enforce_hrd",    "1");
                // header_spacing=0: insert SPS/PPS before every frame so late subscribers
                // can decode from any keyframe — AMF's analog to NVENC's repeat_headers=1.
                dict.set("header_spacing", "0");
            }
            _ => {
                // NVENC (NVIDIA GPUs) — default/existing path.
                // p4/hq: better compression than p3 at minimal extra GPU latency (~1ms).
                dict.set("preset",         "p4");
                dict.set("tune",           "hq");
                // vbr: variable bitrate gives the encoder freedom to use more bits for
                // complex game frames and fewer for static UI — better quality per bit
                // than CBR without exceeding the configured ceiling.
                dict.set("rc",             "vbr");
                // spatial-aq: redistributes bits toward visually detailed areas (sharp
                // edges, text) — essentially free quality gain for screen content.
                dict.set("spatial-aq",     "1");
                // temporal-aq disabled: adds ~1-3ms of GPU analysis per frame and is the
                // primary cause of encode budget overruns under game load. spatial-aq alone
                // handles the quality-per-bit improvement without the latency cost.
                dict.set("aq-strength",    "8"); // default strength; 10 (max) added measurable frame time
                // surfaces=2, delay=0: minimal NVENC pipeline depth, matches hw_frames pool
                // (initial_pool_size above). Reverted from a brief try at 4 — see that
                // field's comment. delay=0 does NOT mean synchronous:
                // GPU encodes asynchronously while the CPU blocks in AcquireNextFrame
                // (~16ms per vsync).  try_harvest() at the top of the next capture
                // iteration finds the packet ready immediately — NVENC takes ~3ms,
                // leaving ~13ms of margin before harvest runs.  CPU never stalls.
                // With delay=1 try_harvest would return EAGAIN (frame N not output until N+1
                // is submitted), which breaks the harvest-top/submit-bottom loop structure.
                dict.set("surfaces",       "2");
                dict.set("delay",          "0");
                // lookahead=0: explicit — p4/hq may otherwise enable 1-frame lookahead
                // which adds a frame of latency and a small amount of extra GPU work.
                dict.set("lookahead",      "0");
                // Embed SPS/PPS before every IDR so late subscribers can decode from any keyframe.
                dict.set("repeat_headers", "1");
            }
        }

        let encoder = video.open_as_with(codec, dict)
            .map_err(|e| format!("[d3d11va] {codec_name} open failed: {e}"))?;

        // Release our local refs; the encoder's AVCodecContext owns the frames ref
        // and the frames context owns the device ref.
        unsafe {
            let mut f = frames_ctx_buf;
            ffi::av_buffer_unref(&mut f);
            let mut d = device_ctx_buf;
            ffi::av_buffer_unref(&mut d);
        }

        // ── 4. Create D3D11 VideoProcessor for BGRA → NV12 ───────────────────
        let video_dev: ID3D11VideoDevice = d3d_device.cast()
            .map_err(|e| format!("Failed to cast to ID3D11VideoDevice: {e}"))?;
        let video_ctx: ID3D11VideoContext = d3d_context.cast()
            .map_err(|e| format!("Failed to cast to ID3D11VideoContext: {e}"))?;

        let content_desc = D3D11_VIDEO_PROCESSOR_CONTENT_DESC {
            InputFrameFormat:  D3D11_VIDEO_FRAME_FORMAT_PROGRESSIVE,
            InputFrameRate:    DXGI_RATIONAL { Numerator: config.fps, Denominator: 1 },
            InputWidth:        src_w,
            InputHeight:       src_h,
            OutputFrameRate:   DXGI_RATIONAL { Numerator: config.fps, Denominator: 1 },
            OutputWidth:       enc_w,
            OutputHeight:      enc_h,
            Usage:             D3D11_VIDEO_USAGE_PLAYBACK_NORMAL,
        };

        let vp_enum = unsafe { video_dev.CreateVideoProcessorEnumerator(&content_desc) }
            .map_err(|e| format!("CreateVideoProcessorEnumerator failed: {e}"))?;
        let vp = unsafe { video_dev.CreateVideoProcessor(&vp_enum, 0) }
            .map_err(|e| format!("CreateVideoProcessor failed: {e}"))?;

        eprintln!("[capture] D3D11VA GPU encoder ready: {src_w}×{src_h} → {enc_w}×{enc_h} @ {} fps", config.fps);

        // Write a fresh debug log for this capture session (truncates the previous one).
        let _log_path = std::env::temp_dir().join("specter_capture_debug.txt");
        let _ = std::fs::write(&_log_path, format!(
            "=== SpecterComs capture session ===\n[encoder] D3D11VA {src_w}x{src_h} -> {enc_w}x{enc_h} @ {}fps\n",
            config.fps));
        eprintln!("[capture] debug log: {}", _log_path.display());

        Ok(Self {
            encoder:     ManuallyDrop::new(encoder),
            frame:       ffmpeg::frame::Video::empty(),
            pts:         0,
            d3d11va:     Some(D3d11vaState { video_dev, video_ctx, d3d_ctx: d3d_context.clone(), vp_enum, vp, blit_tex: None, input_view: None }),
            device_lost: false,
            drained:     false,
            pending_ts:  0,
            codec_name:  if codec_name == "h264_amf" { "h264_amf" } else { "h264_nvenc" },
        })
    }

    /// Returns the AVCDecoderConfigurationRecord from the opened encoder context.
    /// Always populated after avcodec_open2; used to inject SPS+PPS when the
    /// encoder's header-repeat option (repeat_headers on NVENC, header_spacing on
    /// AMF) is silently ignored by some hardware encoder drivers.
    fn extradata(&self) -> &[u8] {
        unsafe {
            let ctx = self.encoder.as_ptr() as *const ffi::AVCodecContext;
            if (*ctx).extradata.is_null() || (*ctx).extradata_size <= 0 {
                &[]
            } else {
                std::slice::from_raw_parts((*ctx).extradata, (*ctx).extradata_size as usize)
            }
        }
    }

    // ── D3D11VA zero-copy encode ──────────────────────────────────────────────
    // Convenience wrapper: stage_frame (CopyResource) + encode_from_blit (VP+NVENC).
    // Used by the WGC paths where frames are already in a local D3D11 texture and
    // no DXGI frame lock needs to be released between the two steps.
    // The DXGI monitor path calls stage_frame + ReleaseFrame + encode_from_blit
    // directly so the DXGI output lock is dropped before the GPU encode runs.
    pub fn encode_d3d11(
        &mut self,
        bgra_tex:     &windows::Win32::Graphics::Direct3D11::ID3D11Texture2D,
        timestamp_ms: u64,
    ) -> Result<super::NalUnit, String>
    {
        self.stage_frame(bgra_tex)?;
        self.encode_from_blit(timestamp_ms)
    }
}

// ── Non-Windows stubs ─────────────────────────────────────────────────────────
#[cfg(not(target_os = "windows"))]
pub struct StatefulEncoder;

#[cfg(not(target_os = "windows"))]
impl StatefulEncoder {
    pub fn new_d3d11va(
        _w: u32, _h: u32,
        _config: &super::CaptureConfig,
        _d3d_device: &windows::Win32::Graphics::Direct3D11::ID3D11Device,
        _d3d_context: &windows::Win32::Graphics::Direct3D11::ID3D11DeviceContext,
    ) -> Result<Self, String> {
        Err("Screen capture is only supported on Windows".to_string())
    }
    pub fn encode_d3d11(
        &mut self,
        _bgra_tex: &windows::Win32::Graphics::Direct3D11::ID3D11Texture2D,
        _timestamp_ms: u64,
    ) -> Result<super::NalUnit, String> {
        Err("Screen capture is only supported on Windows".to_string())
    }
    pub fn submit_frame(&mut self, _timestamp_ms: u64) -> Result<(), String> {
        Err("Screen capture is only supported on Windows".to_string())
    }
    pub fn try_harvest(&mut self) -> Option<super::NalUnit> { None }
    pub fn encode_from_blit(&mut self, _timestamp_ms: u64) -> Result<super::NalUnit, String> {
        Err("Screen capture is only supported on Windows".to_string())
    }
}
