/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_get_jsaddmemberresult_commit: (a: number) => [number, number];
export const __wbg_get_jsaddmemberresult_device_state: (a: number) => [number, number];
export const __wbg_get_jsaddmemberresult_welcome: (a: number) => [number, number];
export const __wbg_jsaddmemberresult_free: (a: number, b: number) => void;
export const __wbg_jsdecryptresult_free: (a: number, b: number) => void;
export const __wbg_jsencryptresult_free: (a: number, b: number) => void;
export const __wbg_jsnewidentity_free: (a: number, b: number) => void;
export const __wbg_set_jsaddmemberresult_commit: (a: number, b: number, c: number) => void;
export const __wbg_set_jsaddmemberresult_device_state: (a: number, b: number, c: number) => void;
export const __wbg_set_jsaddmemberresult_welcome: (a: number, b: number, c: number) => void;
export const add_member: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number];
export const create_group: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const decrypt: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number];
export const encrypt: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number];
export const export_secret: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number, number, number];
export const frame_key_packages: (a: number, b: number) => [number, number];
export const generate_identity: (a: number, b: number) => [number, number, number];
export const generate_key_package: (a: number, b: number) => [number, number, number];
export const group_epoch: (a: number, b: number, c: number, d: number) => [bigint, number, number];
export const group_exists: (a: number, b: number, c: number, d: number) => [number, number, number];
export const group_member_labels: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const join_from_welcome: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const process_commit: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
export const remove_member: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number];
export const __wbg_get_jsdecryptresult_device_state: (a: number) => [number, number];
export const __wbg_get_jsdecryptresult_plaintext: (a: number) => [number, number];
export const __wbg_get_jsencryptresult_ciphertext: (a: number) => [number, number];
export const __wbg_get_jsencryptresult_device_state: (a: number) => [number, number];
export const __wbg_get_jsnewidentity_device_state: (a: number) => [number, number];
export const __wbg_get_jsnewidentity_key_package: (a: number) => [number, number];
export const __wbg_set_jsdecryptresult_device_state: (a: number, b: number, c: number) => void;
export const __wbg_set_jsdecryptresult_plaintext: (a: number, b: number, c: number) => void;
export const __wbg_set_jsencryptresult_ciphertext: (a: number, b: number, c: number) => void;
export const __wbg_set_jsencryptresult_device_state: (a: number, b: number, c: number) => void;
export const __wbg_set_jsnewidentity_device_state: (a: number, b: number, c: number) => void;
export const __wbg_set_jsnewidentity_key_package: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_drop_slice: (a: number, b: number) => void;
export const __wbindgen_start: () => void;
